---
version: "3.9"

services:

  zookeeper:
    image: quay.io/debezium/zookeeper:1.9
    container_name: zookeeper
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888

  kafka:
    image: quay.io/debezium/kafka:1.9
    container_name: kafka
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
      ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_MESSAGE_MAX_BYTES: 10485760

  datagen1:
    image: materialize/datagen:latest
    container_name: datagen1
    depends_on:
      - kafka
    environment:
      KAFKA_BROKERS: kafka:9092
    volumes:
      - ./schemas:/schemas
    entrypoint:
      datagen -s /schemas/schema.json -f json -n 10024 --record-size 1048576 -d
  datagen2:
    image: materialize/datagen:latest
    container_name: datagen2
    depends_on:
      - kafka
    environment:
      KAFKA_BROKERS: kafka:9092
    volumes:
      - ./schemas:/schemas
    entrypoint:
      datagen -s /schemas/schema.json -f json -n 10024 --record-size 1048576 -d
  datagen3:
    image: materialize/datagen:latest
    container_name: datagen3
    depends_on:
      - kafka
    environment:
      KAFKA_BROKERS: kafka:9092
    volumes:
      - ./schemas:/schemas
    entrypoint:
      datagen -s /schemas/schema.json -f json -n 10024 --record-size 1048576 -d
