name: Integration Tests
on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.txt"
      - "examples/**"
    branches:
      - main

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Docker Compose Up
        run: docker compose up --build -d

      - name: Datagen Test Version
        run: docker exec datagen datagen --version

      - name: Produce to Kafka from SQL Schema in JSON Format
        run: docker exec datagen datagen -s /tests/schema2.sql -f json -n 3 --record-size 100 -d

      - name: Produce to Kafka from JSON Schema in JSON Format
        run: docker exec datagen datagen -s /tests/schema.json -f json -n 3 --record-size 100 -d

      - name: Produce to Kafka from Avro Schema in JSON Format
        run: docker exec datagen datagen -s /tests/schema.avsc -f json -n 3 --record-size 100 -d

      - name: Produce to Kafka from SQL Schema in Avro Format
        run: docker exec datagen datagen -s /tests/schema2.sql -f avro -n 3 --record-size 100 -d -w 100

      - name: Produce to Kafka from JSON Schema in Avro Format
        run: docker exec datagen datagen -s /tests/schema.json -f avro -n 3 --record-size 100 -d -w 100 -p json

      - name: Produce to Kafka from Avro Schema in Avro Format
        run: docker exec datagen datagen -s /tests/schema.avsc -f avro -n 3 --record-size 100 -d -w 100 -p avro

      - name: Clean Kafka topic
        run: docker exec datagen datagen -s /tests/schema2.sql -f json -d --clean

      - name: Clean Kafka topic with prefix
        run: docker exec datagen datagen -s /tests/schema2.sql -f json -d --clean --prefix json

      - name: Clean Kafka topic and schema registry
        run: docker exec datagen datagen -s /tests/schema.avsc -f avro -d --clean --prefix avro

      - name: Docker Compose Down
        run: docker compose down -v
